# Generated by Django 5.2.8 on 2025-11-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_images/'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
